"""Add audit_logs and triggers

Revision ID: 6628e951a84b
Revises: 835243caecbe
Create Date: 2026-08-15 23:30:38.805522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6628e951a84b'
down_revision: Union[str, Sequence[str], None] = '835243caecbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_case_id'), 'audit_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_doc_id'), 'audit_logs', ['doc_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    
    context = op.get_context()
    if context.dialect.name == 'mysql':
        op.execute("""
        CREATE TRIGGER prevent_audit_update
        BEFORE UPDATE ON audit_logs
        FOR EACH ROW
        BEGIN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'AUDIT_INTEGRITY_VIOLATION: audit logs are immutable';
        END
        """)
        op.execute("""
        CREATE TRIGGER prevent_audit_delete
        BEFORE DELETE ON audit_logs
        FOR EACH ROW
        BEGIN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'AUDIT_INTEGRITY_VIOLATION: audit logs cannot be deleted';
        END
        """)
        op.execute("""
        CREATE TRIGGER prevent_access_update
        BEFORE UPDATE ON document_access
        FOR EACH ROW
        BEGIN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'AUDIT_INTEGRITY_VIOLATION: document access logs are immutable';
        END
        """)
        op.execute("""
        CREATE TRIGGER prevent_access_delete
        BEFORE DELETE ON document_access
        FOR EACH ROW
        BEGIN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'AUDIT_INTEGRITY_VIOLATION: document access logs cannot be deleted';
        END
        """)
    elif context.dialect.name == 'sqlite':
        op.execute("""
        CREATE TRIGGER prevent_audit_update BEFORE UPDATE ON audit_logs
        BEGIN
            SELECT RAISE(ABORT, 'AUDIT_INTEGRITY_VIOLATION: audit logs are immutable');
        END;
        """)
        op.execute("""
        CREATE TRIGGER prevent_audit_delete BEFORE DELETE ON audit_logs
        BEGIN
            SELECT RAISE(ABORT, 'AUDIT_INTEGRITY_VIOLATION: audit logs cannot be deleted');
        END;
        """)
        op.execute("""
        CREATE TRIGGER prevent_access_update BEFORE UPDATE ON document_access
        BEGIN
            SELECT RAISE(ABORT, 'AUDIT_INTEGRITY_VIOLATION: document access logs are immutable');
        END;
        """)
        op.execute("""
        CREATE TRIGGER prevent_access_delete BEFORE DELETE ON document_access
        BEGIN
            SELECT RAISE(ABORT, 'AUDIT_INTEGRITY_VIOLATION: document access logs cannot be deleted');
        END;
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS prevent_audit_update")
    op.execute("DROP TRIGGER IF EXISTS prevent_audit_delete")
    op.execute("DROP TRIGGER IF EXISTS prevent_access_update")
    op.execute("DROP TRIGGER IF EXISTS prevent_access_delete")
    
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_doc_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_case_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
