"""Add case participants

Revision ID: 835243caecbe
Revises: 90184f5fb009
Create Date: 2026-08-15 23:29:19.927614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835243caecbe'
down_revision: Union[str, Sequence[str], None] = '90184f5fb009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_participants_case_id'), 'case_participants', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_participants_id'), 'case_participants', ['id'], unique=False)
    op.create_index(op.f('ix_case_participants_wallet_address'), 'case_participants', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_participants_wallet_address'), table_name='case_participants')
    op.drop_index(op.f('ix_case_participants_id'), table_name='case_participants')
    op.drop_index(op.f('ix_case_participants_case_id'), table_name='case_participants')
    op.drop_table('case_participants')
    # ### end Alembic commands ###
